# Generated by Django 5.0 on 2024-11-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patienthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientHistory',
        ),
    ]
