# Generated by Django 5.0 on 2024-11-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_status_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scientist', models.ForeignKey(limit_choices_to={'role': 'Scientist'}, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
    ]
