# Generated by Django 4.1.13 on 2024-11-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='doctor',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_issues', to='core.userprofile'),
            preserve_default=False,
        ),
    ]
