# Generated by Django 4.1.13 on 2024-11-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_issue_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='doctor',
        ),
    ]
