# Generated by Django 4.1.13 on 2024-11-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_issue_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_issues', to='core.userprofile'),
        ),
    ]
