# Generated by Django 4.1.13 on 2024-11-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_issue_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='doctor',
        ),
        migrations.AddField(
            model_name='issue',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
