# Generated by Django 4.1.13 on 2024-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_issue_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='specialization',
            field=models.CharField(blank=True, choices=[('dental', 'Dental'), ('brain', 'Brain/Neurology'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('orthopedic', 'Orthopedic'), ('pediatric', 'Pediatric'), ('general', 'General Medicine')], max_length=100, null=True),
        ),
    ]
