# Generated by Django 4.1.13 on 2024-11-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_issue_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='specialization',
        ),
    ]
